---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0  # Update me!
    hooks:
      - id: yamllint
        args: [-c, "./config.yamllint.yaml"]

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.45.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
